### ISSUE TITLE
I received an error for the database, is there a database ??

### ISSUE THREAD

**Issue by hakanonymos** [sambayour/Paypal-payment-integration-in-php#1]
I received an error for the database, is there a database ??

**Comment by sambayour** [comment]
Yes, I will push the mysql dump now

**Comment by hakanonymos** [comment]
OK thank you

**Comment by hakanonymos** [comment]
OK thank you
________________________________
De : sambayour <notifications@github.com>
Envoyé : vendredi 8 mai 2020 22:14
À : sambayour/Paypal-payment-integration-in-php <Paypal-payment-integration-in-php@noreply.github.com>
Cc : hakanonymos <hakanonymos@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [sambayour/Paypal-payment-integration-in-php] I received an error for the database, is there a database ?? (#1)


Closed #1<https://github.com/sambayour/Paypal-payment-integration-in-php/issues/1>.
